project:
  type: book
  output-dir: docs

book:
  page-navigation: true
  title: "Computer Programming"
  author: "phonchi"
  date: "02/17/2023"
  chapters:
    - index.qmd
    - 01_Python.ipynb
    - 02_Flow_control.ipynb
    - 03_Function.ipynb
    - 04_Lists_tuples.ipynb
    - 05_Dictionaries_sets.ipynb
    - 06_Manipulating_string.ipynb
    - 07_Files.ipynb
    - 08_09_OOP.ipynb
    - 10_11_NumPy.ipynb
    - 12_Matplotlib.ipynb
    - 13_SymPy.ipynb
  appendices:
    - 00_Copilot.ipynb
    - 00_SciPy.ipynb
    - 04_Algorithms_sol.ipynb
    - 05_Data_Structure_sol.ipynb
    - 06_Abstract_data_types_sol.ipynb
    - Assignment 1_sol.ipynb
    - Assignment 2_sol.ipynb
    - Assignment 3_sol.ipynb
    - Assignment 4_sol.ipynb
    - Assignment 5_sol.ipynb
    - Assignment 6_sol.ipynb
    - Assignment 7_sol.ipynb
    - Assignment 8_sol.ipynb
    - Assignment 9_sol.ipynb
    - Quiz1_sol.ipynb
    - Quiz2_sol.ipynb
  search:
    location: sidebar
format:
  html:
    theme: cosmo
    cover-image: cover.jpg